### Get XSRF token
GET {{baseUrl}}/heartbeat/?taalIso=be

### Login
POST {{baseUrl}}/inloggen/
X-Xsrf-Token: {{xsrfToken}}

{
  "username": "{{username}}",
  "password": "{{password}}",
  "remember": false
}

### Events
GET {{baseUrl}}/events/?datum=2024-08-04&rooster=4
Cookie: XSRF-TOKEN={{xsrfToken}}
X-Xsrf-Token: {{xsrfToken}}

### RESERVE Event
POST {{baseUrl}}/events/14502/deelname/
Cookie: XSRF-TOKEN={{xsrfToken}}
X-Xsrf-Token: {{xsrfToken}}

### DELETE Event
DELETE {{baseUrl}}/events/14616/deelname/
Cookie: XSRF-TOKEN={{xsrfToken}}
X-Xsrf-Token: {{xsrfToken}}
