name: Flexbox

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "30 6,12,15,21 * * *"
  workflow_dispatch:

jobs:
  sync-gilliam:
    uses: ./.github/workflows/sync-gcal-sportbit.yml
    secrets: inherit

  sync-ariane:
    uses: ./.github/workflows/sync-gcal-sportbit.yml
    secrets: inherit
