name: Flexbox

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 0,12,16 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: Jaid/action-npm-install@v1.2.4
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - run: npm start
