name: Flexbox

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "30 6,12,15,21 * * *"
  workflow_dispatch:

jobs:
  sync-gilliam:
    uses: ./.github/workflows/sync-gcal-sportbit.yml
    secrets: inherit

  sync-ariane:
    uses: ./.github/workflows/sync-gcal-sportbit.yml
    secrets:
      DRY_RUN: ${{secrets.DRY_RUN}}
      NUMBER_OF_WEEKS_TO_RESERVE: ${{secrets.NUMBER_OF_WEEKS_TO_RESERVE}}
      GOOGLE_CALENDAR_ID: ${{secrets.GOOGLE_CALENDAR_ID}}
      GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
      GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
      GOOGLE_REDIRECT_URL: ${{secrets.GOOGLE_REDIRECT_URL}}
      GOOGLE_REFRESH_TOKEN: ${{secrets.GOOGLE_REFRESH_TOKEN}}
      SUPER7_LOGIN: ${{secrets.SUPER7_LOGIN}}
      SUPER7_PASS: ${{secrets.SUPER7_PASS}}
