name: Sync Gcal to Sportbit

on:
  workflow_call:
    secrets:
      DRY_RUN:
      NUMBER_OF_WEEKS_TO_RESERVE:
      GOOGLE_CALENDAR_ID:
      GOOGLE_CLIENT_ID:
      GOOGLE_CLIENT_SECRET:
      GOOGLE_REDIRECT_URL:
      GOOGLE_REFRESH_TOKEN:
      SUPER7_LOGIN:
      SUPER7_PASS:
      JSONBIN_MASTER_KEY:
      JSONBIN_ACCESS_KEY:
      JSONBIN_BIN_ID:
      JSONBIN_ACCOUNT_NAME:

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "Europe/Brussels"
      - uses: actions/checkout@v3
      - uses: asdf-vm/actions/install@v3
      - run: pnpm install
      - name: Run script
        env:
          DRY_RUN: ${{secrets.DRY_RUN}}
          NUMBER_OF_WEEKS_TO_RESERVE: ${{secrets.NUMBER_OF_WEEKS_TO_RESERVE}}
          GOOGLE_CALENDAR_ID: ${{secrets.GOOGLE_CALENDAR_ID}}
          GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
          GOOGLE_REDIRECT_URL: ${{secrets.GOOGLE_REDIRECT_URL}}
          GOOGLE_REFRESH_TOKEN: ${{secrets.GOOGLE_REFRESH_TOKEN}}
          SUPER7_LOGIN: ${{secrets.SUPER7_LOGIN}}
          SUPER7_PASS: ${{secrets.SUPER7_PASS}}
          JSONBIN_MASTER_KEY: ${{secrets.JSONBIN_MASTER_KEY}}
          JSONBIN_ACCESS_KEY: ${{secrets.JSONBIN_ACCESS_KEY}}
          JSONBIN_BIN_ID: ${{secrets.JSONBIN_BIN_ID}}
          JSONBIN_ACCOUNT_NAME: ${{secrets.JSONBIN_ACCOUNT_NAME}}
        run: pnpm start
